# Generated by Django 4.2 on 2023-05-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlistitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_id',
            new_name='session',
        ),
    ]
